[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = [ "poetry-core>=1", "poetry-dynamic-versioning>=1,<2" ]

[project]
name = "cambium-astro"
description = "Astronomy-related stages for Cambium"
readme = "README.md"
license = "MIT"
license-files = [ "LICEN[CS]E*" ]
authors = [
  { name = "Sidrat Research", email = "info@sidratresearch.com" },
  { name = "Mubdi Rahman", email = "mubdi@sidratresearch.com" },
  { name = "Tai Withers", email = "tai@sidratresearch.com" },
  { name = "Hansen Jiang", email = "hansen@sidratresearch.com" },
  { name = "Jennifer Scora", email = "jscora@sidratresearch.com" },
]
requires-python = ">=3.11,<4.0"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Astronomy",
]
dynamic = [ "version" ]
dependencies = [
  "astropy>=8.0.1,<9",
  "cambium>=0.6",
  "matplotlib>=3.11.1,<4",
]
urls.Homepage = "https://github.com/sidratresearch/cambium-astro"
urls.Issues = "https://github.com/sidratresearch/cambium-astro/issues"
scripts.cambium-astro = "cambium_astro.cli:main"

[dependency-groups]
dev = [
  "black>=26.3.1,<27",
  "ipykernel>=7.2,<8",
  "isort>=8.0.1,<9",
  "pre-commit>=4.6,<5",
  "pytest>=9.0.3,<10",
  "tox>=4.53.1,<5",
]

[tool.poetry]
version = "0.0.0"
requires-plugins.poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = [
  "plugin",
] }

[tool.poetry-dynamic-versioning]
enable = true
