"""Macros for cambium-astro."""

import logging

from cambium.macros.macro_utils import Macro, MacroArgs, MacroKwargs
from cambium.tree import TreeSpan
from cambium.utils.other_utils import make_jinja_environment
from cambium.utils.path_utils import path_matches_patterns

from .preview_fits.preview_fits import DEFAULT_ENABLE_PATTERNS

logger = logging.getLogger(__name__)


ListFITSFiles_template = """
{% macro preview_link(filename, preview_href) -%}
  <a href="{{ preview_href }}" aria-label="Preview {{ filename }}">{{ filename }}</a>
{%- endmacro %}
{% macro download_link(filename, download_href) -%}
  <a
      href="{{ download_href }}"
      download="{{ filename }}"
      aria-label="Download {{ filename }}"
  >
      {% include "icon-download.html.jinja" %}
  </a>
{%- endmacro %}

<table>
  <tbody>
    {% for filename, preview_href, download_href in files %}
      <tr>
        {% if preview_href == None %}
          <td align="left">{{ filename }} (no preview available)</td>
        {% else %}
          <td align="left">{{ preview_link(filename, preview_href) }}</td>
        {% endif %}
        <td>{{ download_link(filename, download_href) }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
"""


class ListFITSFiles(Macro):
    """List and link to all FITS files in the current directory."""

    @classmethod
    def apply(
        cls,
        leaf_uuid: str,
        tree: TreeSpan,
        content: str | None,
        args: MacroArgs,
        kwargs: MacroKwargs,
    ) -> str:
        if content is not None:
            logger.warning("cambium_astro.ListFITSFiles does not use start and stop")
        if len(args) > 0:
            logger.warning("cambium_astro.ListFITSFiles does not use parameters")

        recursive = kwargs.get("recursive", False)
        subdirectory = kwargs.get("subdirectory")
        initial_path = tree.leaves["initial_path"][leaf_uuid]

        directory = initial_path.parent

        if subdirectory is not None:
            directory = directory / subdirectory

        rows = []
        for uuid in tree.leaves["uuids"]:
            initial_path = tree.leaves["initial_path"][uuid]
            final_path = tree.leaves["final_path"][uuid]

            # limit to preview leaves, and fits files without previews
            if not path_matches_patterns(initial_path, DEFAULT_ENABLE_PATTERNS):
                continue

            # only check files in the current directory
            try:
                filename = initial_path.relative_to(directory)
            except ValueError:
                continue

            # current directory only, if non-recursive
            if not recursive and len(filename.parts) > 1:
                continue

            # skip the FITS leaves generated by PreviewFITS
            if filename.parts[0] == ".cambium":
                continue

            # set default links
            preview_href, download_href = None, filename

            # update links if we have a preview page
            if final_path.suffix == ".html":
                download_href = (
                    filename / filename.name
                )  # relies on FITSHandlers keeping this consistent
                preview_href = final_path.relative_to(directory)

            # update links if file is in a subdir
            if subdirectory is not None:
                download_href = subdirectory / download_href
                if preview_href is not None:
                    preview_href = subdirectory / preview_href

            rows.append([filename, preview_href, download_href])

        rows.sort(key=lambda row: row[0])  # sort by name

        jinja_environment = make_jinja_environment(tree)
        jinja_template = jinja_environment.from_string(ListFITSFiles_template)

        from cambium.utils.md_html_utils import wrap_with_div

        return wrap_with_div(jinja_template.render(files=rows), "table")
