"""Macros for cambium-astro."""

import logging

from cambium.macros.macro_utils import Macro, MacroArgs, MacroKwargs
from cambium.tree import TreeSpan

from .preview_fits.preview_fits import DEFAULT_ENABLE_PATHS

logger = logging.getLogger(__name__)


class ListFITSFiles(Macro):
    """List and link to all FITS files in the current directory."""

    @classmethod
    def apply(
        cls,
        leaf_uuid: str,
        tree: TreeSpan,
        content: str | None,
        args: MacroArgs,
        kwargs: MacroKwargs,
    ) -> str:
        if content is not None:
            logger.warning("cambium_astro.ListFITSFiles does not use start and stop")
        if len(args) > 0:
            logger.warning("cambium_astro.ListFITSFiles does not use parameters")

        recursive = kwargs.get("recursive", False)
        subdirectory = kwargs.get("subdirectory")
        initial_path = tree.leaves["initial_path"][leaf_uuid]

        directory = initial_path.parent

        if subdirectory is not None:
            directory = directory / subdirectory

        rows = []
        for uuid in tree.leaves["uuids"]:
            initial_path = tree.leaves["initial_path"][uuid]
            final_path = tree.leaves["final_path"][uuid]

            # limit to preview leaves, and fits files without previews
            if f"*{initial_path.suffix}" not in DEFAULT_ENABLE_PATHS:
                continue

            # only check files in the current directory
            try:
                filename = initial_path.relative_to(directory)
            except ValueError:
                continue

            # current directory only, if non-recursive
            if not recursive and len(filename.parts) > 1:
                continue

            # skip the FITS leaves generated by PreviewFITS
            if filename.parts[0] == ".cambium":
                continue

            is_preview = final_path.suffix == ".html"

            # get the preview cell and the link for the download cell
            if is_preview:
                download_href = (
                    filename / filename.name
                )  # relies on FITSHandlers keeping this consistent
                preview_href = final_path.relative_to(directory)
                if subdirectory is not None:
                    preview_href = subdirectory / preview_href
                preview_link = f'<a href="./{preview_href}">{filename}</a>'
            else:
                download_href = filename
                preview_link = f"{filename} (no preview available)"

            # make the download cell
            if subdirectory is not None:
                download_href = subdirectory / download_href
            download_link = f'<a href="./{download_href}">direct download</a>'

            row = "".join(
                f'<td align="left">{cell}</td>'
                for cell in (preview_link, download_link)
            )
            rows.append(f"<tr>{row}</tr>")

        from cambium.utils.md_html_utils import wrap_with_div

        return wrap_with_div(
            ("<table><tbody>" + "".join(rows) + "</tbody></table>"),
            "table",
        )
